<div id="wrapper">
    <!----->
    <nav class="navbar-default navbar-static-top" role="navigation">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <h1> <a class="navbar-brand">Vendas</a></h1>
        </div>
        <div class=" border-bottom">
            <div class="clearfix"></div>

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li>
                            <a id="dashboard" class="hvr-bounce-to-right"><i class="fa fa-dashboard nav_icon "></i><span class="nav-label">Dashboard</span></a>
                        </li>
                        <li>
                            <a id="cadastrar-vendedor" class="hvr-bounce-to-right"><i class="fa fa-dashboard nav_icon "></i><span class="nav-label">Cadastrar Vendedor</span></a>
                        </li>
                        <li>
                            <a id="lancar-venda" class="hvr-bounce-to-right"><i class="fa fa-dashboard nav_icon "></i><span class="nav-label">Lançar Venda</span></a>
                        </li>
                    </ul>
                </div>
            </div>
    </nav>
    <div id="page-wrapper" class="gray-bg dashbard-1">
        <div class="content-main">

        </div>
    </div>
</div>
<script>
    var token = "<?php echo $this->data()["token"]?>"

    $.ajaxSetup({
        headers: {
            'token': token
        }
    });

    $("#cadastrar-vendedor").click(function () {
        $.ajax({
            type: "post",
            url: "vendedor",
            success: function (data) {
                $(".content-main").html(data);
            },
            error: function (error) {
                alert(error.responseJSON.error)
            }
        });
    })

    $("#lancar-venda").click(function () {
        $.ajax({
            type: "post",
            url: "venda",
            success: function (data) {
                $(".content-main").html(data);
            },
            error: function (error) {
                alert(error.responseJSON.error)
            }
        });
    })
</script>