<div id="wrapper">
    <!----->
    <nav class="navbar-default navbar-static-top" role="navigation">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <h1> <a class="navbar-brand">Vendas</a></h1>
        </div>
        <div class=" border-bottom">
            <div class="clearfix"></div>

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li>
                            <a id="dashboard" class="hvr-bounce-to-right"><i class="fa fa-desktop nav_icon "></i><span class="nav-label">Dashboard</span></a>
                        </li>
                        <li>
                            <a id="cadastrar-vendedor" class="hvr-bounce-to-right"><i class="fa fa-user nav_icon "></i><span class="nav-label">Vendedores</span></a>
                        </li>
                        <li>
                            <a id="lancar-venda" class="hvr-bounce-to-right"><i class="fa fa-shopping-cart nav_icon "></i><span class="nav-label">Vendas</span></a>
                        </li>
                        <li>
                            <a id="configuracao" class="hvr-bounce-to-right"><i class="fa fa-gears nav_icon "></i><span class="nav-label">Configurações</span></a>
                        </li>
                    </ul>
                </div>
            </div>
    </nav>
    <div id="page-wrapper" class="gray-bg dashbard-1">
        <div class="content-main">

        </div>
        <div class="content-support">

        </div>
    </div>
</div>
<script>
    var token = "<?php echo $this->data()["token"]?>"

    $.ajaxSetup({
        headers: {
            'token': token
        }
    });

    function openDashboard () {
        $.ajax({
            type: "post",
            url: "dashboard",
            success: function (data) {
                $(".content-main").html(data);
            },
            error: function (error) {
                error = error.responseJSON.error;
                if (error.indexOf("Login") > 0) {
                    function reload() {
                        window.location.reload();
                    }

                    alert(error, reload);
                } else {
                    alert(error);
                }
            }
        });
    }
    $("#dashboard").click(function () {
        openDashboard();
    });

    $("#cadastrar-vendedor").click(function () {
        $.ajax({
            type: "post",
            url: "vendedor",
            success: function (data) {
                let content =  $(".content-main");
                content.empty();
                content.html(data);
            },
            error: function (error) {
                error = error.responseJSON.error;
                if (error.indexOf("Login") > 0) {
                    function reload() {
                        window.location.reload();
                    }

                    alert(error, reload);
                } else {
                    alert(error);
                }
            }
        });
    });

    $("#lancar-venda").click(function () {
        $.ajax({
            type: "post",
            url: "venda",
            success: function (data) {
                $(".content-main").html(data);
            },
            error: function (error) {
                error = error.responseJSON.error;
                if (error.indexOf("Login") > 0) {
                    function reload() {
                        window.location.reload();
                    }

                    alert(error, reload);
                } else {
                    alert(error);
                }
            }
        });
    });

    $("#configuracao").click(function () {
        $.ajax({
            type: "post",
            url: "configuracao",
            success: function (data) {
                $(".content-main").html(data);
            },
            error: function (error) {
                error = error.responseJSON.error;
                if (error.indexOf("Login") > 0) {
                    function reload() {
                        window.location.reload();
                    }

                    alert(error, reload);
                } else {
                    alert(error);
                }
            }
        });
    });

    openDashboard();
</script>