<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>
<head>
    <title>Sistema de Controle de Vendas</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="keywords" content="Minimal Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design"/>
    <script type="application/x-javascript"> addEventListener("load", function () {
        setTimeout(hideURLbar, 0);
    }, false);

    function hideURLbar() {
        window.scrollTo(0, 1);
    } </script>
    <link href="../../../../public/vendor/css/bootstrap.min.css" rel='stylesheet' type='text/css'/>
    <!-- Custom Theme files -->
    <link href="../../../../public/vendor/css/style.css" rel='stylesheet' type='text/css'/>
    <link href="../../../../public/vendor/css/font-awesome.css" rel="stylesheet">
    <script src="../../../../public/vendor/js/jquery.min.js"></script>
    <script src="../../../../public/vendor/js/bootstrap.min.js"></script>
</head>
<body>
<div class="login">
    <h1><a href="index.html">Controle de Vendas</a></h1>
    <div class="login-bottom">
        <h2>Nova Conta</h2>
        <div class="col-md-6">
            <div class="login-mail">
                <input type="text" placeholder="Email" required="">
                <i class="fa fa-envelope"></i>
            </div>
            <div class="login-mail">
                <input type="password" placeholder="Senha" required="">
                <i class="fa fa-lock"></i>
            </div>
            <div class="login-mail">
                <input type="password" placeholder="Senha Novamente" required="">
                <i class="fa fa-lock"></i>
            </div>
            <div class="login-mail">
                <input type="text" placeholder="Token de Autorização" required="">
                <i class="fa fa-key"></i>
            </div>

        </div>
        <div class="col-md-6 login-do">
            <label class="hvr-shutter-in-horizontal login-sub">
                <input type="submit" value="Enviar">
            </label>
            <p>Já tem uma conta?</p>
            <a href="index.html" class="hvr-shutter-in-horizontal">Login</a>
        </div>
        <div class="clearfix"></div>
    </div>
</div>
<!---->
<div class="copy-right">
    <p> &copy; 2016 Minimal. All Rights Reserved | Design by <a href="http://w3layouts.com/" target="_blank">W3layouts</a></p>
</div>

<!---->
<!--scrolling js-->
<script src="../../../../public/vendor/js/jquery.nicescroll.js"></script>
<script src="../../../../public/vendor/js/scripts.js"></script>
<!--//scrolling js-->
</body>
</html>

