<div class="grid-form">
    <div class="grid-form1">
        <h3 id="forms-horizontal">Cadastrar Vendedor</h3>
        <form id="form-vendedor" class="form-horizontal" onsubmit="return false">
            <div class="form-group">
                <label for="id-vendedor" class="col-sm-2 control-label">ID</label>
                <div class="col-sm-10">
                    <select name="id-vendedor" id="id-vendedor" class="form-control1">
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label for="nome-vendedor" class="col-sm-2 control-label hor-form">Nome</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="nome-vendedor" name="nome-vendedor" placeholder="Nome" required>
                </div>
            </div>
            <div class="form-group">
                <label for="email-vendedor" class="col-sm-2 control-label hor-form">Email</label>
                <div class="col-sm-10">
                    <input type="email" class="form-control" id="email-vendedor" name="email-vendedor" placeholder="Email" required>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button id="cadastrar-vendedor" class="btn-primary btn">Cadastrar</button>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="grid-form">
    <div class="grid-form1">
        <h3 id="forms-horizontal">Lista de Vendedores</h3>
        <div class="col-md-3 form-group1 group-mail">
            <label class="control-label ">Data Inicial</label>
            <input type="date" id="data-inicio" class="form-control1 ng-invalid ng-invalid-required" ng-model="model.date" required="">
        </div>
        <div class="col-offset-2 col-md-3 form-group1 group-mail">
            <label class="control-label ">Data Final</label>
            <input type="date" id="data-fim" class="form-control1 ng-invalid ng-invalid-required" ng-model="model.date" required="">
        </div>
        <div class="col-sm-offset-2 col-2 filtro-periodo" >
            <button id="buscar-vendedores" class="btn-primary btn">Buscar</button>
        </div>

        <table id="lista-vendedores" class="table">
            <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Nome</th>
                <th scope="col">Email</th>
                <th scope="col">Comissão no Período</th>
                <th scope="col">Vendas</th>
            </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>
<script>
    $( document ).ready(function() {
        var vendedores = {};
        $('#form-vendedor').submit(function (event) {
            event.preventDefault();

            let form = $(this);
            let data = form.serialize();
            $.ajax({
                type: "post",
                url: "cadastrarVendedor",
                data: data,
                success: function (data) {
                    let id = $("#id-vendedor").val();
                    form[0].reset();
                    if (id === 'Novo') {
                        alert('Vendedor Cadastrado com Sucesso.');
                    } else {
                        alert('Vendedor Atualizado com Sucesso.');
                    }
                    buscarVendedores();
                },
                error: function (error) {
                    error = error.responseJSON.error;
                    if (error.indexOf("Login") > 0) {
                        function reload() {
                            window.location.reload();
                        }

                        alert(error, reload);
                    } else {
                        alert(error);
                    }
                }
            });
        });

        $("#id-vendedor").change(function () {
            let select = $("#id-vendedor");

            let vendedor = vendedores[select.val()];

            if (vendedor) {
                $("#nome-vendedor").val(vendedor.nome);
                $("#email-vendedor").val(vendedor.email);
            } else {
                $("#nome-vendedor").val('');
                $("#email-vendedor").val('');
            }

        });

        function adicionarEventoSelecionarLinha() {
            $("#lista-vendedores tbody tr").click(function () {
                let tr = $(this);
                let table = tr.parents("table");
                let alltrs = table.find("tr");
                alltrs.removeClass("selected");
                tr.addClass("selected");

                let td = tr.find(".id");

                let select = $("#id-vendedor");

                select.find('option').prop('selected', false);
                select.find('option[value="' + td.text() + '"]').prop('selected', true);
                select.change();
            })
        }

        function adicionarEventoMostrarVendas() {
            $(".mostrar-vendas").click(function () {
                $.ajax({
                    type: "post",
                    url: "vendasVendedor",
                    success: function (data) {
                        $("#myModal").modal('hide');
                        $(".content-support").html(data);
                    },
                    error: function (error) {
                        error = error.responseJSON.error;
                        if (error.indexOf("Login") > 0) {
                            function reload() {
                                window.location.reload();
                            }

                            alert(error, reload);
                        } else {
                            alert(error);
                        }
                    }
                });
            })
        }

        function buscarVendedores() {
            let lista = $("#lista-vendedores > tbody");
            let select = $("#id-vendedor");
            lista.empty();
            select.empty();
            select.append(new Option('Novo', 'Novo'));

            function inserirVendedor(element, index, array) {
                let linha = "<tr>";
                linha += "<td class='id'>" + element.id + "</td>";
                linha += "<td>" + element.nome + "</td>";
                linha += "<td>" + element.email + "</td>";
                linha += "<td>" + element.comissao + "</td>";
                linha += "<td>" + "<a class='mostrar-vendas'>Mostrar</a>"  + "</td>";
                linha += "</tr>";
                lista.append(linha);

                vendedores[element.id] = element;


                select.append(new Option(element.id, element.id));
            }

            let dataInicio = $("#data-inicio").val();
            let dataFim = $("#data-fim").val();
            let data = {
                "data-inicio": dataInicio,
                "data-fim": dataFim,
            };

            $.ajax({
                type: "post",
                url: "buscarTodosVendedores",
                data: data,
                success: function (data) {
                    data = data.data;
                    data.forEach(inserirVendedor);
                    adicionarEventoSelecionarLinha();
                    adicionarEventoMostrarVendas();
                },
                error: function (error) {
                    error = error.responseJSON.error;
                    if (error.indexOf("Login") > 0) {
                        function reload() {
                            window.location.reload();
                        }

                        alert(error, reload);
                    } else {
                        alert(error);
                    }
                }
            });
        }

        buscarVendedores();

        $('#buscar-vendedores').click(function (event) {
            buscarVendedores();
        });
    });
</script>